# Comprehensive H3 Prediction Experiment Configuration  
# Phase 4: XGBoost with 42 high-quality features and feature selection

defaults:
  - base_h3_experiment

experiment:
  name: "comprehensive_h3_prediction"
  description: "Phase 4: XGBoost with comprehensive features and selection"
  phase: 4

# Data configuration
data:
  training_data_path: "data/processed/training_sets/comprehensive_h3_sequences.pkl"
  test_size: 0.2

# Model configuration
model:
  type: "xgboost"
  parameters:
    n_estimators: 100
    max_depth: 8
    learning_rate: 0.1
    random_state: 42
    n_jobs: -1

# Training configuration
training:
  use_feature_selection: true
  top_k_features: 25
  
# Evaluation configuration
evaluation:
  distance_sample_size: 500
