# Massive H3 Prediction Experiment Configuration
# Phase 5: Large-scale training with all available data and features

defaults:
  - experiment_h3_base

experiment:
  name: "massive_h3_prediction"
  description: "Phase 5: Large-scale training with maximum data and features"
  phase: 5

# Data configuration
data:
  training_data_path: "data/processed/training_sets/massive_h3_sequences.pkl"
  test_size: 0.15  # Smaller test set for massive data

# Model configuration
model:
  type: "xgboost"
  parameters:
    n_estimators: 200
    max_depth: 10
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42
    n_jobs: -1

# Training configuration
training:
  use_feature_selection: true
  top_k_features: 25
  memory_efficient: true

# Evaluation configuration
evaluation:
  distance_sample_size: 1000  # Larger sample for massive data

# Performance configuration
performance:
  chunked_loading: true
  chunk_size: 10000
  memory_monitoring: true
