test:
  name: "feature_extraction_validation"
  type: "feature_extraction"
  description: "Test feature extraction pipeline and H3 conversion"

data_source:
  test_data_path: "data/raw/ais_cape_data_2024.pkl"
  vessel_limit: 3
  records_per_vessel: 100

features:
  test_h3_conversion: true
  test_vessel_features: true
  expected_feature_count: 54
  validate_feature_quality: true

output:
  show_sample_features: true
  validate_data_types: true
  performance_metrics: true
