# TFT Experiment Configuration
# Extends default.yaml with TFT-specific parameters

defaults:
  - ../default

model:
  name: "tft"
  hidden_size: 128
  attention_head_size: 4
  dropout: 0.1
  hidden_continuous_size: 16
  
training:
  max_epochs: 100
  learning_rate: 0.01
  
optimization:
  study_name: "tft_optimization"
  param_space:
    hidden_size:
      type: "categorical"
      choices: [64, 128, 256]
    attention_head_size:
      type: "categorical"
      choices: [1, 2, 4, 8]
    dropout:
      type: "float"
      low: 0.0
      high: 0.3
      step: 0.05
    learning_rate:
      type: "float"
      low: 0.001
      high: 0.1
      log: true
