data_loading:
  max_vessels: 3
  use_duckdb: false
terminal_discovery:
  min_stationary_hours: 0.5
  min_vessels_for_terminal: 1
  stationary_speed_threshold: 1.0
trajectory_extraction:
  h3_resolution: 5
  min_journey_length: 3
  speed_threshold_knots: 0.5
  time_gap_hours: 12
