"""
Constants for the AIS forecasting and shipping lane discovery system.
"""

# Data processing constants
DEFAULT_H3_RESOLUTION = 6
MAX_VESSELS_SAFETY_LIMIT = 10000
PROGRESS_REPORT_INTERVAL = 100

# Journey segmentation constants
DEFAULT_TIME_GAP_THRESHOLD_HOURS = 24
MIN_JOURNEY_LENGTH_POINTS = 5
MAX_JOURNEY_LENGTH_POINTS = 1000

# Terminal clustering constants
DEFAULT_TERMINAL_EPS_DEGREES = 0.05
DEFAULT_TERMINAL_MIN_SAMPLES = 3
MIN_TERMINAL_VISITS = 5

# Route clustering constants  
DEFAULT_ROUTE_EPS = 1.5
DEFAULT_ROUTE_MIN_SAMPLES = 2
DTW_PROGRESS_REPORT_INTERVAL = 100
MAX_DTW_SEQUENCES = 1000  # Performance limit

# Visualization constants
DEFAULT_MAP_CENTER = [-33.9, 18.4]  # Cape Town
DEFAULT_MAP_ZOOM = 8
MIN_MARKER_SIZE = 5
MAX_MARKER_SIZE = 20
MARKER_SIZE_SCALE_FACTOR = 100

# File formats
SUPPORTED_DATA_FORMATS = ['.pkl', '.parquet', '.csv']
DEFAULT_OUTPUT_FORMAT = 'parquet'
GEOPACKAGE_DRIVER = 'GPKG'

# Geographic bounds (Cape Town region)
CAPE_TOWN_LAT_MIN = -35.0
CAPE_TOWN_LAT_MAX = -32.0
CAPE_TOWN_LON_MIN = 16.0
CAPE_TOWN_LON_MAX = 20.0

# Performance limits
DEFAULT_MEMORY_LIMIT_GB = 45
DEFAULT_CPU_THREADS = 14
CHUNK_SIZE_LARGE_DATASETS = 10000

# Validation thresholds
MIN_SILHOUETTE_SCORE = 0.3
MIN_CLUSTER_SIZE = 2
MAX_OUTLIER_PERCENTAGE = 50.0
